package com.testSSH.domain;
// Generated 2016-9-13 7:02:33 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int id;
	private String name;
	private String email;
	private Date hiredate;

	public Employee() {
	}

	public Employee(int id, String name, String email, Date hiredate) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.hiredate = hiredate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

}
