package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

/**
 * Localprovince generated by hbm2java
 */
public class Localprovince implements java.io.Serializable {

	private int lpId;
	private String lpName;

	public Localprovince() {
	}

	public Localprovince(int lpId, String lpName) {
		this.lpId = lpId;
		this.lpName = lpName;
	}

	public int getLpId() {
		return this.lpId;
	}

	public void setLpId(int lpId) {
		this.lpId = lpId;
	}

	public String getLpName() {
		return this.lpName;
	}

	public void setLpName(String lpName) {
		this.lpName = lpName;
	}

}
