package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Photocomment generated by hbm2java
 */
public class Photocomment implements java.io.Serializable {

	private Integer id;
	private Photo photo;
	private Users users;
	private String content;
	private Date comTime;

	public Photocomment() {
	}

	public Photocomment(Photo photo, Users users, String content, Date comTime) {
		this.photo = photo;
		this.users = users;
		this.content = content;
		this.comTime = comTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Photo getPhoto() {
		return this.photo;
	}

	public void setPhoto(Photo photo) {
		this.photo = photo;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getComTime() {
		return this.comTime;
	}

	public void setComTime(Date comTime) {
		this.comTime = comTime;
	}

}
