package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Senior generated by hbm2java
 */
public class Senior implements java.io.Serializable {

	private Integer id;
	private City city;
	private Town town;
	private String name;
	private Set userseniors = new HashSet(0);

	public Senior() {
	}

	public Senior(String name) {
		this.name = name;
	}

	public Senior(City city, Town town, String name, Set userseniors) {
		this.city = city;
		this.town = town;
		this.name = name;
		this.userseniors = userseniors;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Town getTown() {
		return this.town;
	}

	public void setTown(Town town) {
		this.town = town;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserseniors() {
		return this.userseniors;
	}

	public void setUserseniors(Set userseniors) {
		this.userseniors = userseniors;
	}

}
