package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Techschool generated by hbm2java
 */
public class Techschool implements java.io.Serializable {

	private Integer id;
	private City city;
	private Town town;
	private String name;
	private Set userses = new HashSet(0);

	public Techschool() {
	}

	public Techschool(String name) {
		this.name = name;
	}

	public Techschool(City city, Town town, String name, Set userses) {
		this.city = city;
		this.town = town;
		this.name = name;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Town getTown() {
		return this.town;
	}

	public void setTown(Town town) {
		this.town = town;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
