package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * University generated by hbm2java
 */
public class University implements java.io.Serializable {

	private Integer id;
	private Country country;
	private Province province;
	private String name;
	private Set useruniversities = new HashSet(0);

	public University() {
	}

	public University(String name) {
		this.name = name;
	}

	public University(Country country, Province province, String name, Set useruniversities) {
		this.country = country;
		this.province = province;
		this.name = name;
		this.useruniversities = useruniversities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUseruniversities() {
		return this.useruniversities;
	}

	public void setUseruniversities(Set useruniversities) {
		this.useruniversities = useruniversities;
	}

}
