package com.testSSH.domain;
// Generated 2016-9-20 8:09:50 by Hibernate Tools 5.1.0.Beta1

/**
 * Usercom generated by hbm2java
 */
public class Usercom implements java.io.Serializable {

	private Integer ucId;
	private Integer ucUserId;
	private String ucName;
	private String ucDescribe;
	private Integer ucTrade;
	private Integer ucTradeInfo;
	private Integer ucJob;
	private Integer ucJobInfo;
	private String ucDate;

	public Usercom() {
	}

	public Usercom(Integer ucUserId, String ucName, String ucDescribe, Integer ucTrade, Integer ucTradeInfo,
			Integer ucJob, Integer ucJobInfo, String ucDate) {
		this.ucUserId = ucUserId;
		this.ucName = ucName;
		this.ucDescribe = ucDescribe;
		this.ucTrade = ucTrade;
		this.ucTradeInfo = ucTradeInfo;
		this.ucJob = ucJob;
		this.ucJobInfo = ucJobInfo;
		this.ucDate = ucDate;
	}

	public Integer getUcId() {
		return this.ucId;
	}

	public void setUcId(Integer ucId) {
		this.ucId = ucId;
	}

	public Integer getUcUserId() {
		return this.ucUserId;
	}

	public void setUcUserId(Integer ucUserId) {
		this.ucUserId = ucUserId;
	}

	public String getUcName() {
		return this.ucName;
	}

	public void setUcName(String ucName) {
		this.ucName = ucName;
	}

	public String getUcDescribe() {
		return this.ucDescribe;
	}

	public void setUcDescribe(String ucDescribe) {
		this.ucDescribe = ucDescribe;
	}

	public Integer getUcTrade() {
		return this.ucTrade;
	}

	public void setUcTrade(Integer ucTrade) {
		this.ucTrade = ucTrade;
	}

	public Integer getUcTradeInfo() {
		return this.ucTradeInfo;
	}

	public void setUcTradeInfo(Integer ucTradeInfo) {
		this.ucTradeInfo = ucTradeInfo;
	}

	public Integer getUcJob() {
		return this.ucJob;
	}

	public void setUcJob(Integer ucJob) {
		this.ucJob = ucJob;
	}

	public Integer getUcJobInfo() {
		return this.ucJobInfo;
	}

	public void setUcJobInfo(Integer ucJobInfo) {
		this.ucJobInfo = ucJobInfo;
	}

	public String getUcDate() {
		return this.ucDate;
	}

	public void setUcDate(String ucDate) {
		this.ucDate = ucDate;
	}

}
